# Generated by Django 4.0.3 on 2022-03-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duck_blog', '0002_rename_blog_blogpost_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_date',
        ),
    ]
